apiVersion: v1
appVersion: "2.27.0"
description: "Dex federated authentication service"
name: dex
version: 1.4.0
icon: https://github.com/coreos/dex/blob/master/Documentation/logos/dex-horizontal-color.png
sources:
- https://github.com/coreos/dex
- https://github.com/sl1pm4t/dex-k8s-authenticator/tree/master/charts/dex
maintainers:
- name: Matt Morrison
  email: matt.morrison@ditto.live
